# Generated by Django 3.0.4 on 2020-03-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('redirect_link', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('view_at', models.DateTimeField(null=True)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('tname', models.CharField(max_length=200, null=True)),
                ('pubdate', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'History',
            },
        ),
    ]
