# Generated by Django 3.0.4 on 2020-03-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shouye', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
